### PR TITLE
Added the exception when querying for 'Yearly' data.

### PR DESCRIPTION
**Pull request by angryvoegi**
Hi Frank

First of all, thanks for the nice package!
I added the exception when querying for yearly data since the 'todate' parameter breaks the API request.

Kind regards
Nicco

### CODE REVIEW

**Comment by angryvoegi** [comment]
Hi Frank

To my previous pull request I added the 'priceSpread' and 'scheduledExchange' parsers to the JAO PublicationTool Client.

Kind regards
Nicco

**Comment by fboerman** [comment]
hi @angryvoegi  many thanks for this work! I provided a couple of minor comments. Could you process them?
for the future its better if the two seperate changes, changing webclient and changing puto client, are in seperate pull requests, but for now its fine.
Thanks!

**Comment by angryvoegi** [comment]
Hi Frank. Thanks for your reply. Unfortunatelly, I am unable to see/find your comments.
Of course, it was a mistake that both commits went into the same pull request.
Kind regards

**Comment by fboerman** [comment]
hi @angryvoegi  oh that is strange :( I am not that familiar with the code review concept of github. I will paste the comments below:

* pandas has much better timezone support so I would like to keep the type hinting to pandas only. If the user whishes he can always force a datetime
* I rather have writen out "query_scheduled_exchanges"

**Comment by fboerman** [comment]
thanks! ill merge it and push it out!

**Comment by angryvoegi** [comment]
Perfect, thank you 😄

**Pull request merged**
